language: node_js

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

node_js:
  - '0.10.26'

before_script:
  - 'npm install -g bower grunt-cli karma'
  - 'bower install'

script: grunt test:all
